# Generated by Django 5.0.3 on 2024-03-20 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bin_id', models.CharField(max_length=100, unique=True)),
                ('level', models.FloatField(default=0)),
                ('weight', models.FloatField(default=0)),
                ('last_empty_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
